// ========== الكلمات الجاهزة حسب المجالات ==========
const vocabularyDB = {
    business: [
        { word: "Innovation", translation: "ابتكار", example: "Innovation drives progress in business.", level: 1, category: "business" },
        { word: "Strategy", translation: "استراتيجية", example: "A good strategy ensures long-term success.", level: 1, category: "business" },
        { word: "Leadership", translation: "قيادة", example: "Leadership inspires teams to achieve goals.", level: 1, category: "business" },
        { word: "Investment", translation: "استثمار", example: "Smart investment grows wealth over time.", level: 1, category: "business" },
        { word: "Marketing", translation: "تسويق", example: "Digital marketing reaches global audiences.", level: 1, category: "business" },
        { word: "Entrepreneur", translation: "رائد أعمال", example: "The entrepreneur launched a successful startup.", level: 1, category: "business" },
        { word: "Revenue", translation: "إيرادات", example: "Company revenue increased by 20%.", level: 1, category: "business" },
        { word: "Profit", translation: "ربح", example: "The business made a healthy profit.", level: 1, category: "business" },
        { word: "Stakeholder", translation: "صاحب مصلحة", example: "Stakeholders expect transparency.", level: 1, category: "business" },
        { word: "Scalability", translation: "قابلية التوسع", example: "Scalability is crucial for growth.", level: 1, category: "business" }
    ],
    technology: [
        { word: "Algorithm", translation: "خوارزمية", example: "The algorithm processes data efficiently.", level: 1, category: "technology" },
        { word: "Database", translation: "قاعدة بيانات", example: "The database stores user information.", level: 1, category: "technology" },
        { word: "Artificial Intelligence", translation: "الذكاء الاصطناعي", example: "AI is transforming many industries.", level: 1, category: "technology" },
        { word: "Cloud Computing", translation: "الحوسبة السحابية", example: "Cloud computing enables remote access.", level: 1, category: "technology" },
        { word: "Encryption", translation: "تشفير", example: "Encryption protects sensitive data.", level: 1, category: "technology" },
        { word: "Firewall", translation: "جدار حماية", example: "A firewall blocks unauthorized access.", level: 1, category: "technology" },
        { word: "API", translation: "واجهة برمجة تطبيقات", example: "API allows applications to communicate.", level: 1, category: "technology" },
        { word: "Responsive", translation: "متجاوب", example: "Responsive design works on all devices.", level: 1, category: "technology" },
        { word: "Framework", translation: "إطار عمل", example: "The framework speeds up development.", level: 1, category: "technology" },
        { word: "Cybersecurity", translation: "الأمن السيبراني", example: "Cybersecurity protects against threats.", level: 1, category: "technology" }
    ],
    travel: [
        { word: "Destination", translation: "وجهة", example: "Paris is a popular destination.", level: 1, category: "travel" },
        { word: "Itinerary", translation: "جدول الرحلة", example: "Plan your itinerary in advance.", level: 1, category: "travel" },
        { word: "Accommodation", translation: "إقامة", example: "We found comfortable accommodation.", level: 1, category: "travel" },
        { word: "Passport", translation: "جواز سفر", example: "Don't forget your passport.", level: 1, category: "travel" },
        { word: "Visa", translation: "تأشيرة", example: "You need a visa for that country.", level: 1, category: "travel" },
        { word: "Adventure", translation: "مغامرة", example: "Every trip is an adventure.", level: 1, category: "travel" },
        { word: "Souvenir", translation: "تذكار", example: "I bought a souvenir from the market.", level: 1, category: "travel" },
        { word: "Landmark", translation: "معلم بارز", example: "The Eiffel Tower is a famous landmark.", level: 1, category: "travel" },
        { word: "Booking", translation: "حجز", example: "Make your booking early.", level: 1, category: "travel" },
        { word: "Luggage", translation: "أمتعة", example: "Travel light with minimal luggage.", level: 1, category: "travel" }
    ],
    medical: [
        { word: "Diagnosis", translation: "تشخيص", example: "Early diagnosis improves outcomes.", level: 1, category: "medical" },
        { word: "Prescription", translation: "وصفة طبية", example: "Take the prescription to the pharmacy.", level: 1, category: "medical" },
        { word: "Symptom", translation: "عَرَض", example: "Fever is a common symptom.", level: 1, category: "medical" },
        { word: "Vaccine", translation: "لقاح", example: "The vaccine prevents disease.", level: 1, category: "medical" },
        { word: "Immunity", translation: "مناعة", example: "A healthy diet boosts immunity.", level: 1, category: "medical" },
        { word: "Chronic", translation: "مزمن", example: "Chronic conditions require ongoing care.", level: 1, category: "medical" },
        { word: "Therapy", translation: "علاج", example: "Physical therapy aids recovery.", level: 1, category: "medical" },
        { word: "Surgery", translation: "جراحة", example: "The surgery was successful.", level: 1, category: "medical" },
        { word: "Diagnostic", translation: "تشخيصي", example: "Diagnostic tests identify diseases.", level: 1, category: "medical" },
        { word: "Rehabilitation", translation: "تأهيل", example: "Rehabilitation helps regain strength.", level: 1, category: "medical" }
    ]
};

// ========== المصطلحات العلمية (أكثر من 200) ==========
const scientificTermsDB = [
    // الرياضيات
    { word: "Calculus", translation: "حساب التفاضل والتكامل", example: "Calculus is used in physics and engineering.", category: "علمي" },
    { word: "Algebra", translation: "الجبر", example: "Algebra deals with symbols and equations.", category: "علمي" },
    { word: "Geometry", translation: "الهندسة", example: "Geometry studies shapes and spaces.", category: "علمي" },
    { word: "Trigonometry", translation: "علم المثلثات", example: "Trigonometry relates angles to side lengths.", category: "علمي" },
    { word: "Theorem", translation: "نظرية", example: "The Pythagorean theorem is famous.", category: "علمي" },
    { word: "Hypothesis", translation: "فرضية", example: "The hypothesis was tested experimentally.", category: "علمي" },
    { word: "Algorithm", translation: "خوارزمية", example: "The algorithm processes data efficiently.", category: "علمي" },
    { word: "Matrix", translation: "مصفوفة", example: "A matrix is a rectangular array of numbers.", category: "علمي" },
    { word: "Derivative", translation: "مشتقة", example: "The derivative represents rate of change.", category: "علمي" },
    { word: "Integral", translation: "تكامل", example: "The integral calculates area under a curve.", category: "علمي" },
    { word: "Probability", translation: "احتمال", example: "Probability measures the likelihood of events.", category: "علمي" },
    { word: "Statistics", translation: "إحصاء", example: "Statistics involves collecting and analyzing data.", category: "علمي" },
    { word: "Equation", translation: "معادلة", example: "Solve the equation for x.", category: "علمي" },
    { word: "Variable", translation: "متغير", example: "Let x be the variable in this equation.", category: "علمي" },
    { word: "Constant", translation: "ثابت", example: "Pi is a mathematical constant.", category: "علمي" },
    { word: "Infinity", translation: "ما لا نهاية", example: "Infinity is larger than any number.", category: "علمي" },
    { word: "Symmetry", translation: "تناظر", example: "The butterfly has perfect symmetry.", category: "علمي" },
    // الفيزياء
    { word: "Gravity", translation: "الجاذبية", example: "Gravity pulls objects toward Earth.", category: "علمي" },
    { word: "Velocity", translation: "سرعة متجهة", example: "Velocity includes both speed and direction.", category: "علمي" },
    { word: "Acceleration", translation: "تسارع", example: "Acceleration is the rate of change of velocity.", category: "علمي" },
    { word: "Momentum", translation: "زخم", example: "Momentum is mass times velocity.", category: "علمي" },
    { word: "Energy", translation: "طاقة", example: "Energy cannot be created or destroyed.", category: "علمي" },
    { word: "Kinetic", translation: "حركي", example: "Kinetic energy is energy of motion.", category: "علمي" },
    { word: "Potential", translation: "كامن", example: "Potential energy is stored energy.", category: "علمي" },
    { word: "Quantum", translation: "كم", example: "Quantum mechanics describes tiny particles.", category: "علمي" },
    { word: "Photon", translation: "فوتون", example: "Light consists of photons.", category: "علمي" },
    { word: "Electron", translation: "إلكترون", example: "Electrons orbit the nucleus.", category: "علمي" },
    { word: "Proton", translation: "بروتون", example: "Protons have a positive charge.", category: "علمي" },
    { word: "Neutron", translation: "نيوترون", example: "Neutrons have no electric charge.", category: "علمي" },
    { word: "Atom", translation: "ذرة", example: "Atoms are the building blocks of matter.", category: "علمي" },
    { word: "Molecule", translation: "جزيء", example: "A water molecule has two hydrogen atoms.", category: "علمي" },
    { word: "Thermodynamics", translation: "ديناميكا حرارية", example: "Thermodynamics studies heat and work.", category: "علمي" },
    { word: "Entropy", translation: "إنتروبيا", example: "Entropy measures disorder in a system.", category: "علمي" },
    // الكيمياء
    { word: "Chemical", translation: "مادة كيميائية", example: "A chemical reaction produces new substances.", category: "علمي" },
    { word: "Reaction", translation: "تفاعل", example: "The reaction released heat.", category: "علمي" },
    { word: "Catalyst", translation: "محفز", example: "A catalyst speeds up a reaction.", category: "علمي" },
    { word: "Acid", translation: "حمض", example: "Acids have a pH less than 7.", category: "علمي" },
    { word: "Base", translation: "قاعدة", example: "Bases have a pH greater than 7.", category: "علمي" },
    { word: "pH", translation: "الرقم الهيدروجيني", example: "Pure water has a pH of 7.", category: "علمي" },
    { word: "Compound", translation: "مركب", example: "Water is a chemical compound.", category: "علمي" },
    { word: "Solution", translation: "محلول", example: "Salt dissolved in water is a solution.", category: "علمي" },
    { word: "Solvent", translation: "مذيب", example: "Water is a common solvent.", category: "علمي" },
    { word: "Solute", translation: "مذاب", example: "The solute dissolves in the solvent.", category: "علمي" },
    { word: "Precipitation", translation: "ترسيب", example: "Precipitation forms a solid in a solution.", category: "علمي" },
    // الأحياء
    { word: "Photosynthesis", translation: "البناء الضوئي", example: "Plants use photosynthesis to make food.", category: "علمي" },
    { word: "Mitochondria", translation: "الميتوكوندريا", example: "Mitochondria produce energy in cells.", category: "علمي" },
    { word: "Nucleus", translation: "النواة", example: "The nucleus contains DNA.", category: "علمي" },
    { word: "DNA", translation: "الحمض النووي", example: "DNA carries genetic information.", category: "علمي" },
    { word: "RNA", translation: "الحمض النووي الريبوزي", example: "RNA helps make proteins.", category: "علمي" },
    { word: "Gene", translation: "جين", example: "Genes determine inherited traits.", category: "علمي" },
    { word: "Chromosome", translation: "كروموسوم", example: "Humans have 23 pairs of chromosomes.", category: "علمي" },
    { word: "Cell", translation: "خلية", example: "Cells are the basic unit of life.", category: "علمي" },
    { word: "Tissue", translation: "نسيج", example: "Muscle tissue helps movement.", category: "علمي" },
    { word: "Organ", translation: "عضو", example: "The heart is a vital organ.", category: "علمي" },
    { word: "System", translation: "جهاز", example: "The digestive system processes food.", category: "علمي" },
    { word: "Evolution", translation: "تطور", example: "Evolution explains species diversity.", category: "علمي" },
    { word: "Species", translation: "نوع", example: "Each species is unique.", category: "علمي" },
    { word: "Ecosystem", translation: "نظام بيئي", example: "An ecosystem includes living and non-living things.", category: "علمي" },
    { word: "Biodiversity", translation: "تنوع حيوي", example: "Biodiversity is important for ecosystems.", category: "علمي" },
    { word: "Habitat", translation: "موطن", example: "Protect the natural habitat of animals.", category: "علمي" },
    { word: "Symbiosis", translation: "تكافل", example: "Symbiosis is a close relationship between species.", category: "علمي" },
    { word: "Parasite", translation: "طفيلي", example: "A parasite lives on a host.", category: "علمي" },
    { word: "Virus", translation: "فيروس", example: "Viruses cause many diseases.", category: "علمي" },
    { word: "Bacteria", translation: "بكتيريا", example: "Some bacteria are beneficial.", category: "علمي" },
    { word: "Fungi", translation: "فطريات", example: "Mushrooms are a type of fungi.", category: "علمي" },
    { word: "Eukaryote", translation: "حقيقية النواة", example: "Plants and animals are eukaryotes.", category: "علمي" },
    { word: "Prokaryote", translation: "بدائية النواة", example: "Bacteria are prokaryotes.", category: "علمي" },
    { word: "Metabolism", translation: "أيض", example: "Metabolism converts food to energy.", category: "علمي" },
    { word: "Homeostasis", translation: "اتزان داخلي", example: "The body maintains homeostasis.", category: "علمي" },
    // علوم الحاسوب
    { word: "Software", translation: "برمجيات", example: "Software runs on computers.", category: "علمي" },
    { word: "Hardware", translation: "عتاد", example: "Hardware includes the physical components.", category: "علمي" },
    { word: "Programming", translation: "برمجة", example: "Programming involves writing code.", category: "علمي" },
    { word: "Code", translation: "كود", example: "Code is written in programming languages.", category: "علمي" },
    { word: "Debugging", translation: "تصحيح أخطاء", example: "Debugging fixes errors in code.", category: "علمي" },
    { word: "Compiler", translation: "مترجم", example: "A compiler converts code to machine language.", category: "علمي" },
    { word: "Network", translation: "شبكة", example: "Computers connect through a network.", category: "علمي" },
    // علم النفس
    { word: "Psychology", translation: "علم النفس", example: "Psychology studies the mind and behavior.", category: "علمي" },
    { word: "Cognition", translation: "إدراك", example: "Cognition involves thinking and understanding.", category: "علمي" },
    { word: "Memory", translation: "ذاكرة", example: "Memory stores and retrieves information.", category: "علمي" },
    { word: "Perception", translation: "إدراك حسي", example: "Perception interprets sensory information.", category: "علمي" },
    { word: "Emotion", translation: "عاطفة", example: "Emotions influence our decisions.", category: "علمي" },
    { word: "Behavior", translation: "سلوك", example: "Observable behavior can be measured.", category: "علمي" },
    // علم الفلك
    { word: "Astronomy", translation: "علم الفلك", example: "Astronomy studies celestial objects.", category: "علمي" },
    { word: "Galaxy", translation: "مجرة", example: "The Milky Way is our galaxy.", category: "علمي" },
    { word: "Star", translation: "نجم", example: "The Sun is a star.", category: "علمي" },
    { word: "Planet", translation: "كوكب", example: "Earth is a planet.", category: "علمي" },
    { word: "Orbit", translation: "مدار", example: "The Moon orbits Earth.", category: "علمي" },
    { word: "Telescope", translation: "تلسكوب", example: "A telescope sees distant objects.", category: "علمي" },
    { word: "Comet", translation: "مذنب", example: "Comets have icy nuclei.", category: "علمي" },
    { word: "Asteroid", translation: "كويكب", example: "Asteroids orbit the Sun.", category: "علمي" }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { vocabularyDB, scientificTermsDB };
}